### PR TITLE
Fix build with GHC 9.2

### LINKED ISSUE #19: Build failure with GHC 9.2.1
```
Data/BloomFilter/Util.hs:43:38: error:
    • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
    • In the first argument of ‘W32#’, namely
        ‘(x# `uncheckedShiftL#` i#)’
      In the expression: W32# (x# `uncheckedShiftL#` i#)
      In an equation for ‘shiftL’:
          shiftL (W32# x#) (I# i#) = W32# (x# `uncheckedShiftL#` i#)
   |
43 |     shiftL (W32# x#) (I# i#) = W32# (x# `uncheckedShiftL#` i#)
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^

Data/BloomFilter/Util.hs:46:38: error:
    • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
    • In the first argument of ‘W32#’, namely
        ‘(x# `uncheckedShiftRL#` i#)’
      In the expression: W32# (x# `uncheckedShiftRL#` i#)
      In an equation for ‘shiftR’:
          shiftR (W32# x#) (I# i#) = W32# (x# `uncheckedShiftRL#` i#)
   |
46 |     shiftR (W32# x#) (I# i#) = W32# (x# `uncheckedShiftRL#` i#)
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build bloomfilter-2.0.1.0.
```

### PR DESCRIPTION
**Pull request by sjakobi**
…and setup CI on GitHub Actions.

Fixes #19.

### CODE REVIEW

**Comment by sjakobi** [comment]
I've checked that CI works in https://github.com/sjakobi/bloomfilter/pull/1.

**Comment by blackgnezdo** [comment]
Any chance this can be merged and then released? This prevents `aws` package and then transitively `git-annex` from building with ghc-9.2.

**Comment by sjakobi** [comment]
Since the sole maintainer, @bos, hasn't been active on GitHub for a while, it would probably be best if someone would volunteer to [take over](https://wiki.haskell.org/Taking_over_a_package) and maintain this package.

FWIW, I'm not currently interested in serving as a maintainer for this package.

**Comment by arrowd** [comment]
@bos Can you, please, take a look at this PR?

**Comment by Bodigrim** [comment]
@arrowd someone has to step up and ask to take over. My understanding is that @bos is not maintaining his Haskell packages any longer.

**Comment by joeyh** [comment]
I suppose git-annex is one of the major users of bloomfilter now. As its maintainer I'm willing to do some maintenance of bloomfilter if necessary. But I don't have any deep expertise in bloom filters and fear I would not be able to do more than basic keep it working maintenance..

**Comment by Bodigrim** [comment]
I think even a very basic maintenance is better than none, so I'd like to encourage you to take over the packge.

**Comment by joeyh** [comment]
@bos if it's ok with you, I am considering transferring bloomfilter to https://github.com/haskell-pkg-janitors and maintaining it there (also assuming it's ok with them)

**Comment by Bodigrim** [comment]
I'd suggest sending an email to @bos, his GitHub account seems abandoned.

**Comment by joeyh** [comment]
@bos has agreed to pass maintenace to me. 

https://github.com/haskell-pkg-janitors/bloomfilter is the new repository. I've applied this fix there and will release as soon as we sort out hackage permissions.

**Comment by joeyh** [comment]
released in 2.0.1.1
